### ISSUE TITLE
[Feature, API Extension] Grid getters

### ISSUE THREAD

**Issue by robertodr** [bast/numgrid#11]
Currently, `get_grid` returns an array with points coordinates and weights. It could be useful to have multiple ways to get the grid once it has been formed:
1. Get just the grid points coordinates;
2. Get just the point weights;
3. Get just x/y/z grid points coordinates.

Moreover, if I understand correctly the grid generation, there is one Lebedev-Laikov (LL) grid involved (only input parameter is the maximum angular momentum). The full grid is then the tensor product of the angular grid and the radial grid. Thus it would be cool to have functions to handle the angular grid that parallel the ones for the total integration grid:
1. Get LL points coordinates and weights [x, y, z, w];
2. Get LL points coordinates [x, y, z];
3. Get LL weights [w]; 
4. Get LL x/y/z grid points coordinates.

**Comment by bast** [comment]
Good suggestions! One related question that I have been debating with myself is whether the library should allocate the grid (current situation) or whether the caller should allocate it. In the latter case there are less risks for memory leaks and memory corruption and issues with garbage collection but perhaps the API becomes more clumsy? Client allocating can also be error prone if the allocation is too short.

**Comment by robertodr** [comment]
I don't know what's best. What is the most natural option to have the most idiomatic way of using the Python API? I think it's worth turning the problem around and design the low-level interfaces based on how the high-level interface should look.

**Comment by bast** [comment]
Good strategy. I think the Python API should do this:
```
out = lib(in)
```
For me it would be weird to do this:
```
lib(in, inout)
```
One problem with the first one is that `out` can get out of scope but then the allocated memory is left behind. I think I need to read more on how other libs do that.

**Comment by bast** [comment]
I need to talk to Ole Martin about it :-)

**Comment by bast** [comment]
But once I get more clarity in my head I will implement your suggestion above, it makes complete sense.

**Comment by bast** [comment]
Just noting here that the conclusion that we have reached with Ole Martin is that it is useful to allocate on the client side of the C interface. For Python one might need a thin extra layer that allocates and returns a reference to an object.

**Comment by robertodr** [comment]
Do you and/or @olemb have some toy code or pseudocode showing this approach?

**Comment by bast** [comment]
I am working on a tiny demo example for future reference.

**Comment by bast** [comment]
Here is a little demo https://github.com/bast/cffi-mem-alloc-example. Have checked it with Valgrind.

**Comment by bast** [comment]
I believe this is now implemented. Closing.
