### ISSUE TITLE
[Enhancement] Use Psi4 versioning machinery

### ISSUE THREAD

**Issue by robertodr** [bast/numgrid#14]
Psi4 Python scripts and machinery to manage versioning are more reliable and descriptive than hardcoding a version to a file: http://www.psicode.org/psi4manual/1.1/manage_git.html
However:
- Psi4 versioning complies with [PEP 440](https://www.python.org/dev/peps/pep-0440/) and uses MAJOR.MINOR versioning with alpha, beta and candidate pre-releases rather than semantic versioning.
- The change will have to be done with direct push access to the master branch.

**Comment by bast** [comment]
Thanks! I plan to rework this which anyway when introducing a `setup.py` to place the code on PyPI.

**Comment by bast** [comment]
I am closing this for the moment. At least I managed now to move the version to one single file. PRs to make this more elegant are most welcome but the current solution is I think OK for the moment.
