### ISSUE TITLE
Target "numgrid-objects" of type OBJECT_LIBRARY may not be linked into

### ISSUE THREAD

**Issue by bast** [bast/numgrid#33]
Working on it and I almost have a solution. @scemama

**Comment by bast** [comment]
Also adding @heikef since she originally reported the problem and so that she is informed about my progress on this.

**Comment by heikef** [comment]
Thanks for working on this, Radovan!

**Comment by scemama** [comment]
Thank you! If you need, I can help.

**Comment by bast** [comment]
Thanks - basically I have a solution but want to test it a bit. My plan is to upload a new version to PyPI before the week is over.

**Comment by bast** [comment]
It's not forgotten - was busy running behind a grant application deadline but I will look at the compilation problem today or tomorrow.

**Comment by bast** [comment]
OK I have a solution, just need to clean up ugly commit history. Tomorrow morning I will hopefully resolve this.

**Comment by bast** [comment]
Finally fixed - thanks for patience! The fix was easy but there was a lot of other stuff I wanted to resolve before minting a new version on PyPI which is now done.

**Comment by heikef** [comment]
Thank you for your time and effort to fix this.

**Comment by scemama** [comment]
Thanks, it works for me too!

**Comment by bast** [comment]
Cool! :-)
