### ISSUE TITLE
pip install  / basis-set-exchange version

### ISSUE THREAD

**Issue by lnw** [bast/numgrid#35]
On my machine, 'pip install numgrid' fails with some version problem with respect to basis-set-exchange. Specifically, the command returns: 

pip install numgrid
DEPRECATION: Python 2.7 will reach the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 won't be maintained after that date. A future version of pip will drop support for Python 2.7.
Collecting numgrid
  Using cached https://files.pythonhosted.org/packages/46/94/2099ab1ed4593c677f2fc0095704390001fc77d9943877074464d45a0d3f/numgrid-1.1.0.tar.gz
Collecting cffi==1.12.3 (from numgrid)
  Using cached https://files.pythonhosted.org/packages/8d/e9/0c8afd1579e5cf7bc0f06fbcd7cdb954cbc0baadd505973949a99337da1c/cffi-1.12.3-cp27-cp27mu-manylinux1_x86_64.whl
Collecting numpy==1.16.3 (from numgrid)
  Using cached https://files.pythonhosted.org/packages/e1/72/179a78b565ecf01fe98dab6417581d30acac15c2d93c49f93169ebea99b1/numpy-1.16.3-cp27-cp27mu-manylinux1_x86_64.whl
Collecting basis_set_exchange==0.6.9 (from numgrid)
  ERROR: Could not find a version that satisfies the requirement basis_set_exchange==0.6.9 (from numgrid) (from versions: 0.4, 0.4.1, 0.4.2, 0.4.3, 0.4.5, 0.5, 0.5.1, 0.5.2, 0.5.3, 0.5.4, 0.5.5, 0.5.6, 0.5.7, 0.5.8, 0.6.0, 0.6.1, 0.6.2, 0.6.3, 0.6.4)
ERROR: No matching distribution found for basis_set_exchange==0.6.9 (from numgrid)

Is that a problem in numgrid, or basis-set-exchange, or user-related? It is neither clear to me where the 0.6.9 comes from (numgrid mentiones only 0.7.0) nor where the list of versions up to 0.6.4 comes from.

**Comment by bast** [comment]
The error is interesting. See:
- https://github.com/dftlibs/numgrid/blob/master/setup.py#L70
- https://pypi.org/project/basis-set-exchange/#history

I will very soon try to reproduce it.

**Comment by bast** [comment]
Please try with Python 3. I should document better that Python 2 is unsupported since it hits end of life in 2020.

**Comment by lnw** [comment]
Indeed, that works!

Unfortunately, in the current Centos the default is still python2.7.  Installing python-pip3 is possible but slightly more complicated.

Similarly, Centos 7 ships a 'cmake' and a 'cmake3', but given that the numgrid setup requires cmake3.x, one needs to be careful.  Debian on the other hand, ships only 'cmake' which is a cmake3.x ...
