### ISSUE TITLE
pip installing numgrid tries to install an older version of numpy (1.16.3) by removing the existing version

### ISSUE THREAD

**Issue by manassharma07** [bast/numgrid#37]
Is it possible to make the requirements not dependent on the NumPy version.

When I pip installed numgrid, it downloaded an older version of NumPy and installed that after removing the newer version I already had.

**Comment by bast** [comment]
This is a good suggestion. I have learned later that for libraries like this one, one should be careful with pinning library dependencies. I will fix that shortly by not pinning `numpy` and `cffi` dependencies, and publish a new version.

**Comment by manassharma07** [comment]
Thanks for replying and such a great library!

**Comment by bast** [comment]
Fixed in 29f94b78522f8a5e2e083cdc8f2aaafa24e96ed8.
New package is out: https://pypi.org/project/numgrid/1.1.2/

Thanks again for the good suggestion!
