### ISSUE TITLE
A silly question on recommendations about generating a grid

### ISSUE THREAD

**Issue by manassharma07** [bast/numgrid#38]
I am new to numerical grid business, and finding it really hard to form a clear picture in my mind about some things.

1. I am familiar with PySCF and am able to use/modify the grids used by PySCF for numerical integration.
2. In PySCF I just set a grid level b/w 0 (coarse) to 9 (fine) and get a grid of the requested density.
3. Using numgrid however, I wan't able to quite understand the recommended values to use for generating a grid. 
This is because I am not very familiar with various concepts. 

It is really good that numgrid offers such flexibility with options, **but for a newbie like me I was wondering if there could be a simple way to generate a grid by just a giving the desired level??** 

Alternatively, I could do with some advice on how to set the parameters. 

For example, from what I understand the parameters that affect the grid are the 
```
radial_precision = 1.0e-12
min_num_angular_points = 86
max_num_angular_points = 302
alpha_max = [11720.0, 13.01, 13.01]  # O, H, H
max_l_quantum_numbers = [2, 1, 1]  # O, H, H
alpha_min = [[0.3023, 0.2753, 1.185],  # O
             [0.122, 0.727],  # H
             [0.122, 0.727]]  # H
```
But using these default options, and comparing the result of the XC energy calculated on a grid generated using these parameters differs from that of PySCF.

I tried using a higher value of `min_num_angular_points` and `max_num_angular_points` but  the results were a hit and miss kind of situation. 

Even when using `new_atom_grid_bse` with a very big basis set like de2-TZVPPD, the results were a case of a hit and miss. 

I can't seem to figure out a formula on how to gradually increase the accuracy of my integrals when adjusting the parameters.

I would like to be able to see the grids get denser and the results get better, which is not the case for now.

It is also possible that the way I am calculating the energies is wrong. 
For ex: I just take the `x,y,z,w ` returned by 
```
numgrid.get_grid(context,
                                  num_centers,
                                  center_index,
                                  x_coordinates_bohr,
                                  y_coordinates_bohr,
                                  z_coordinates_bohr,
                                  proton_charges)
```
And use these to set the grid for PySCF calculations. Do we need an extra step in between? like normalising the weights or something else?

Would really appreciate some help.

Thanks again for the wonderful library.

**Comment by manassharma07** [comment]
I guess I was drunk when trying it out. After 3 hours I realise that I had my atomic coordinates mixed up. 

Am able to get the correct/expected results now.

And the accuracy gradually increases as expected when increasing the number of min and max_num_angular_points.

Similarly for other parameters. 

Thanks again, and sorry for the dumb question.

**Comment by bast** [comment]
Glad it works now. But the suggestion to make it easier to select a "level" is a good one and not the first time I hear it so it would be good to make this a bit easier and clearer indeed.

**Comment by manassharma07** [comment]
In the PySCF code https://github.com/pyscf/pyscf/blob/master/pyscf/dft/gen_grid.py, at line 607
they give a function to map the levels with angular grid order.

I am using that for now at least for the angular grid part. They also have a function to map the radial grid level but from what I understand, numgrid does radial thing differently.

So for radial grid exponents I guess I would just use the `new_atom_grid_bse` to get something based on the basis set I am using.

**Comment by bast** [comment]
You will still need to select `radial_precision`. The smaller, the better, the larger grid. Default in Dalton (AFAICS) is 1.0e-11.
