### ISSUE TITLE
How to generate grid to calculate magnetizability using GIMIC

### ISSUE THREAD

**Issue by patrashantigopal** [bast/numgrid#47]
Dear Users,

I have installed numgrid on ubuntu using pip command. I want to calculate the grid data for molecules for the calculation of magnetizability. Please help me how I can generate the grid file (gridfile.grd). Please tell step-wise. I am not an expert in the Linux system. Looking forward.

Thanks and regards,
Shanti

**Comment by bast** [comment]
Please start with this example: https://github.com/dftlibs/numgrid#python-example

First step would be to try to generate the example grid without modifying that file. But this may require some Python knowledge (at the end you may need to add some print statements to write the grid to file).

Once that is working, I would then adapt the molecule and basis.
