### ISSUE TITLE
Release package for Python>=3.11

### ISSUE THREAD

**Issue by manassharma07** [bast/numgrid#57]
Is there any plan to provide a pypi package for numgrid which is compatible with Python >=3.11?

**Comment by bast** [comment]
Sorry that I did not see this earlier. I will fix this.

**Comment by manassharma07** [comment]
No worries at all! I appreciate the library and your efforts.

**Comment by alfercorral** [comment]
Is there any update on this issue? I tried with Python 3.12 and could not pip install the package. Thanks

**Comment by yachmena** [comment]
Dear Radovan, would be much appreciated if you could release the package for Python 3.12
(it was a pleasure meeting you in Tromso back 2010 or 11 :) )

**Comment by bast** [comment]
Sorry to all that I forgot to this again. I will release new versions hopefully tonight.

**Comment by manassharma07** [comment]
Thanks a lot!!

**Comment by bast** [comment]
I finally released packages for Python 3.10, 3.11, and 3.12. Thanks for patience!

**Comment by manassharma07** [comment]
Thank you so much!!! Appreciate it!
