### ISSUE TITLE
[Feature] make it possible/easy to save a grid in numpy format

### ISSUE THREAD

**Issue by bast** [bast/numgrid#9]
@robertodr

**Comment by robertodr** [comment]
I've patched up this workaround:
```Python
size = numgrid.get_num_points(context)
grid = numgrid.get_grid(context)

ffi = FFI()
T = ffi.getctype(ffi.typeof(grid).item)
ngrid = numpy.frombuffer(ffi.buffer(grid, size*ffi.sizeof(T)), 'f8')
numpy.save('grid', ngrid)
```
Either implement the patching at the Python API level _or_ provide the Python API by wrapping the C++ API directly using  _e.g._ PyBind11.

**Comment by bast** [comment]
I think with the current API, where data is stored client-side this became a non-issue. I have documented an example here: https://github.com/dftlibs/numgrid#saving-grid-in-numpy-format
